---
title: "Measuring Open Science"
subtitle: "Open Science Retreat 2024 Project Summary"
author:
  - name: Lotte van Burgsteden
    orcid: 
  - name: Tanya van Goch
    orcid:   
  - name: Bogdana Huma
    orcid:     
  - name: Anne Marie Meijer
    orcid: 0009-0005-0550-5432
  - name: Hanne Oberman
    orcid: 0000-0003-3276-2141
  - name: Iris Smal
    orcid: 0000-0003-4511-9008
format: 
  html:
    self-contained: true
---

The Measuring Open Science team collected, reviewed, and analyzed existing research into open science practices. As a team, we developed an interactive overview of open science surveys, which may be used e.g. to reuse questionnaire items on different open science practices.

Our initial goal for this retreat was to work towards improving Utrecht University's Open Science Monitor, a survey about Open Science practices which runs every two years and is scheduled for this summer. The new version of the survey could then be used by other universities in the Netherlands and beyond. Knowing to what extent academics have adopted or are planning to adopt Open Science practices as well as what challenges and benefits they perceive to be associated with Open Science is crucial for coming up with programmes and policies that encourage Open Science adoption.

This topic was proposed by Hanne Oberman who works at Utrecht University and has "inside information" about the ins and outs of the Open Science Monitor ([https://www.uu.nl/en/research/open-science/knowledge-center/open-science-monitor](https://www.uu.nl/en/research/open-science/knowledge-center/open-science-monitor); [https://zenodo.org/communities/ospuu/](https://zenodo.org/communities/ospuu/)). Hanne shared some of the main challenges the survey is facing, namely low response rates and questions that were not tailored to a multidisciplinary academic population. We brainstormed possible solutions for the first problem and arrived at (1) keeping the survey time short (around 5 minutes), and (2) involving individuals in leadership roles in the survey distribution. To address the second issue, we embarked on a short literature review of existing Open Science questionnaires. A quick search yielded about 20 studies conducted in the last 11 years. About half of the surveys targeted a global population, consisting of researchers at all career stages. Most of the surveys recruited participants from all disciplines. There was some diversity in the focus of the survey. While a few covered a variety of Open Science topics, several surveys focused on a specific dimension of Open Science, most often Open Access or Open Data. 

A dashboard for visualizing the findings is available here: [https://hanneoberman.shinyapps.io/os-surveys/](https://hanneoberman.shinyapps.io/os-surveys/) (with persistent identifier on Zenodo: [https://doi.org/10.5281/zenodo.10932820](https://doi.org/10.5281/zenodo.10932820) and code on GitHub: [https://github.com/oscutrecht/OpenScienceSurveys](https://github.com/oscutrecht/OpenScienceSurveys)) and an overview of these studies can be found [here](https://docs.google.com/spreadsheets/d/1JuRPvEEaBwA2nWU8ptUF7Uq8jrtwlt3etAj5PvRcT40/edit#gid=0). We also inventoried the psychological constructs measured by the various surveys and identified seven constructs: awareness, attitudes, behavior, intention, barriers, benefits and conditions. From here, the next step would be to collect all questions associated with each construct in an accessible form that would allow anyone (re-)designing an Open Science survey to peruse them.
